apiVersion: v1
kind: ConfigMap
metadata:
  name: app-micronout-config
  namespace: labs
  labels:
    projeto: projeto-1
    app: app-micronout
    team: devops
    env: lab
data:
  mockapi-path-prefix: mockapi.io
  MOCKAPI_VERSION: api/v1