apiVersion: v1
kind: Service
metadata:
  name: app-micronout-service-lb
  namespace: labs
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/vultr-loadbalancer-label: "labs-service-lb"
    service.beta.kubernetes.io/vultr-loadbalancer-algorithm: "least_connections"
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-check-interval: "10"
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-response-timeout: "5"
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-unhealthy-threshold: "5"
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-healthy-threshold: "5"    
spec:
  type: LoadBalancer
  selector:
    app:  app-micronout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080