apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-micronout
  namespace: labs
  labels:
    projeto: projeto-1
    app: app-micronout
    stack: micronaut
    team: devops
    env: lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-micronout
  template:
    metadata:
      labels:
        app: app-micronout
    spec:
      containers:
        - name: app-micronout
          image: ewr.vultrcr.com/kuberneteslabcontainerregistry/kubernetes-labs-app-micronout:develop
          resources:
            limits:
              memory: "800Mi"
              cpu: "500m"
            requests:
              memory: "400Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          env:
            - name: MOCKAPI_PATH_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: app-micronout-config
                  key: mockapi-path-prefix    
            - name: MOCKAPI_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-micronout-config
                  key: MOCKAPI_VERSION                           
            - name: MOCKAPI_PROJECT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-micronout-secret
                  key: MOCKAPI_PROJECT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 1