apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-labs-app-micronout
  namespace: kubernetes-labs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-labs-app-micronout
  template:
    metadata:
      labels:
        app: kubernetes-labs-app-micronout
    spec:
      containers:
        - name: kubernetes-labs-app-micronout
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          resources:
            limits:
              memory: "800Mi"
              cpu: "500m"
            requests:
              memory: "400Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-labs-app-micronout-service
  namespace: kubernetes-labs
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-labs-app-micronout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080