micronaut:
  application:
    name: "kubernetes-labs-app-micronout"
  server:
    host: 0.0.0.0
    port: 8080

mockapi:
  protocol: "https"
  host: ${MOCKAPI_PROJECT_SECRET}
  prefix: ${MOCKAPI_PREFIX}
  port: 443
  version: ${MOCKAPI_VERSION}
  base-url: "${mockapi.protocol}://${mockapi.host}.${mockapi.prefix}:${mockapi.port}/${mockapi.version}"
