micronaut:
  application:
    name: "kubernetes-labs-app-micronout"
  server:
    host: 0.0.0.0
    port: 8080

mockapi:
  protocol: "http"
  host: ${MOCKAPI_PROJECT_SECRET}
  port: 443
  path-prefix: "mockapi.io/api/v1"
  base-url: "${mockapi.protocol}://${mockapi.host}:${mockapi.port}/${mockapi.path-prefix}"
