micronaut:
  application:
    name: kubernetes-labs-app-micronout
  server:
    host: 0.0.0.0
    port: 8080

mockapi:
  protocol: https
  project-secret: ${MOCKAPI_PROJECT_SECRET}
  host: .mockapi.io
  prefix: api/v1